//Types for Email Validate
export const EMAIL_VALIDATE_REQUEST = 'EMAIL_VALIDATE_REQUEST';
export const EMAIL_VALIDATE_SUCCESS = 'EMAIL_VALIDATE_SUCCESS';
export const EMAIL_VALIDATE_FAILURE = 'EMAIL_VALIDATE_FAILURE';

//Types for Login
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

//Types for saving signup response
export const SAVE_SIGNUP_REQUEST = 'SAVE_SIGNUP_REQUEST';

//Types for logout
export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';

//Types for Megic Login
export const MEGIC_LOGIN_REQUEST = 'MEGIC_LOGIN_REQUEST';
export const MEGIC_LOGIN_SUCCESS = 'MEGIC_LOGIN_SUCCESS';
export const MEGIC_LOGIN_FAILURE = 'MEGIC_LOGIN_FAILURE';

//Types for Megic Login
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

//Types for Get Stylist Info
export const STYLIST_INFO_REQUEST = 'STYLIST_INFO_REQUEST';
export const STYLIST_INFO_SUCCESS = 'STYLIST_INFO_SUCCESS';
export const STYLIST_INFO_FAILURE = 'STYLIST_INFO_FAILURE';

//Types for signup object
export const SIGNUP_OBJ_TRACK = 'SIGNUP_OBJ_TRACK';
export const SIGNUP_OBJ_SUCCESS = 'SIGNUP_OBJ_SUCCESS';
export const SIGNUP_OBJ_CLEAR = 'SIGNUP_OBJ_CLEAR';

//Types for signup create
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//Types for social links
export const SOCIAL_LINKS_SUBMIT_REQUEST = 'SOCIAL_LINKS_SUBMIT_REQUEST';
export const SOCIAL_LINKS_SUBMIT_SUCCESS = 'SOCIAL_LINKS_SUBMIT_SUCCESS';
export const SOCIAL_LINKS_SUBMIT_FAILURE = 'SOCIAL_LINKS_SUBMIT_FAILURE';

//Types for social links
export const SUBMIT_PACKAGE_REQUEST = 'SUBMIT_PACKAGE_REQUEST';
export const SUBMIT_PACKAGE_SUCCESS = 'SUBMIT_PACKAGE_SUCCESS';
export const SUBMIT_PACKAGE_FAILURE = 'SUBMIT_PACKAGE_FAILURE';

//Types for style quiz object
export const STYLE_QUIZ_OBJ_TRACK = 'STYLE_QUIZ_OBJ_TRACK';
export const STYLE_QUIZ_OBJ_SUCCESS = 'STYLE_QUIZ_OBJ_SUCCESS';
export const STYLE_QUIZ_OBJ_CLEAR = 'STYLE_QUIZ_OBJ_CLEAR';

//Types for style quiz
export const STYLE_QUIZ_REQUEST = 'STYLE_QUIZ_REQUEST';
export const STYLE_QUIZ_SUCCESS = 'STYLE_QUIZ_SUCCESS';
export const STYLE_QUIZ_FAILURE = 'STYLE_QUIZ_FAILURE';

//Types for scheduleQuiz obj
export const SCHEDULE_QUIZ_OBJ_TRACK = 'SCHEDULE_QUIZ_OBJ_TRACK';
export const SCHEDULE_QUIZ_OBJ_SUCCESS = 'SCHEDULE_QUIZ_OBJ_SUCCESS';
export const SCHEDULE_QUIZ_OBJ_CLEAR = 'SCHEDULE_QUIZ_OBJ_CLEAR';

//Types for scheduleQuiz 
export const SCHEDULE_QUIZ_REQUEST = 'SCHEDULE_QUIZ_REQUEST';
export const SCHEDULE_QUIZ_SUCCESS = 'SCHEDULE_QUIZ_SUCCESS';
export const SCHEDULE_QUIZ_FAILURE = 'SCHEDULE_QUIZ_FAILURE';

//Types for Address List Get
export const ADDRESS_LIST_REQUEST = 'ADDRESS_LIST_REQUEST';
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS';
export const ADDRESS_LIST_FAILURE = 'ADDRESS_LIST_FAILURE';

//Types of Add Address Obj
export const ADD_ADDRESS_OBJ_TRACK = 'ADD_ADDRESS_OBJ_TRACK';
export const ADD_ADDRESS_OBJ_SUCCESS = 'ADD_ADDRESS_OBJ_SUCCESS';
export const ADD_ADDRESSZ_OBJ_CLEAR = 'ADD_ADDRESSZ_OBJ_CLEAR';

//Types of Add Address
export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAILURE = 'ADD_ADDRESS_FAILURE';

//Types of Remove Address
export const REMOVE_ADDRESS_REQUEST = 'REMOVE_ADDRESS_REQUEST';
export const REMOVE_ADDRESS_SUCCESS = 'REMOVE_ADDRESS_SUCCESS';
export const REMOVE_ADDRESS_FAILURE = 'REMOVE_ADDRESS_FAILURE';

//Types of Edit Address
export const EDIT_ADDRESS_REQUEST = 'EDIT_ADDRESS_REQUEST';
export const EDIT_ADDRESS_SUCCESS = 'EDIT_ADDRESS_SUCCESS';
export const EDIT_ADDRESS_FAILURE = 'EDIT_ADDRESS_FAILURE';

//Types of Area Get
export const AREA_LIST_REQUEST = 'AREA_LIST_REQUEST';
export const AREA_LIST_SUCCESS = 'AREA_LIST_SUCCESS';
export const AREA_LIST_FAILURE = 'AREA_LIST_FAILURE';

//Types of Package Request 
export const PACKAGE_REQUEST_LOADING = 'PACKAGE_REQUEST_LOADING';
export const PACKAGE_REQUEST_SUCCESS = 'PACKAGE_REQUEST_SUCCESS';
export const PACKAGE_REQUEST_FAILURE = 'PACKAGE_REQUEST_FAILURE';

//Types of Package Request Obj
export const PACKAGE_REQUEST_OBJ_TRACK = 'PACKAGE_REQUEST_OBJ_TRACK';
export const PACKAGE_REQUEST_OBJ_SUCCESS = 'PACKAGE_REQUEST_OBJ_SUCCESS';
export const PACKAGE_REQUEST_OBJ_CLEAR = 'PACKAGE_REQUEST_OBJ_CLEAR';

//Types of Update Sizes&Fits Obj
export const UPDATE_OBJ_TRACK = 'UPDATE_OBJ_TRACK';
export const UPDATE_OBJ_SUCCESS = 'UPDATE_OBJ_SUCCESS';
export const UPDATE_OBJ_CLEAR = 'UPDATE_OBJ_CLEAR';

//Types of Update Sizes&Fits 
export const UPDATE_REQUEST_LOADING = 'UPDATE_REQUEST_LOADING';
export const UPDATE_REQUEST_SUCCESS = 'UPDATE_REQUEST_SUCCESS';
export const UPDATE_REQUEST_FAILURE = 'UPDATE_REQUEST_FAILURE';

//Types of MySizes Obj
export const MY_SIZES_OBJ_TRACK = 'MY_SIZES_OBJ_TRACK';
export const MY_SIZES_OBJ_SUCCESS = 'MY_SIZES_OBJ_SUCCESS';
export const MY_SIZES_OBJ_CLEAR = 'MY_SIZES_OBJ_CLEAR';

//Types of MySize Request
export const MY_SIZES_REQUEST = 'MY_SIZES_REQUEST';
export const MY_SIZES_SUCCESS = 'MY_SIZES_SUCCESS';
export const MY_SIZES_FAILURE = 'MY_SIZES_FAILURE';

//Types of MyStyles Request
export const MY_STYLES_REQUEST = 'MY_STYLES_REQUEST';
export const MY_STYLES_SUCCESS = 'MY_STYLES_SUCCESS';
export const MY_STYLES_FAILURE = 'MY_STYLES_FAILURE';

//Types of My Preferences Obj
export const MY_PREFERENCES_OBJ_TRACK = 'MY_PREFERENCES_OBJ_TRACK';
export const MY_PREFERENCES_OBJ_SUCCESS = 'MY_PREFERENCES_OBJ_SUCCESS';
export const MY_PREFERENCES_OBJ_CLEAR = 'MY_PREFERENCES_OBJ_CLEAR';

//Types of My Preferences Request
export const MY_PREFERENCES_REQUEST = 'MY_PREFERENCES_REQUEST';
export const MY_PREFERENCES_SUCCESS = 'MY_PREFERENCES_SUCCESS';
export const MY_PREFERENCES_FAILURE = 'MY_PREFERENCES_FAILURE';

//Types of Feedback Request
export const FEED_BACK_REQUEST = 'FEED_BACK_REQUEST';
export const FEED_BACK_SUCCESS = 'FEED_BACK_SUCCESS';
export const FEED_BACK_FAILURE = 'FEED_BACK_FAILURE';

//Types for Update Profile object
export const PROFILE_OBJ_TRACK = 'SIGNUP_OBJ_TRACK';
export const PROFILE_OBJ_SUCCESS = 'SIGNUP_OBJ_SUCCESS';
export const PROFILE_OBJ_CLEAR = 'SIGNUP_OBJ_CLEAR';

//Types for Update Profile
export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

//Types for Change Password
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

//Types for Update profile pic
export const PROFILE_PICTURE_REQUEST = 'PROFILE_PICTURE_REQUEST';
export const PROFILE_PICTURE_SUCCESS = 'PROFILE_PICTURE_SUCCESS';
export const PROFILE_PICTURE_FAILURE = 'PROFILE_PICTURE_FAILURE';

//Types for Invitation history pic
export const INVITATION_HISTORY_REQUEST = 'INVITATION_HISTORY_REQUEST';
export const INVITATION_HISTORY_SUCCESS = 'INVITATION_HISTORY_SUCCESS';
export const INVITATION_HISTORY_FAILURE = 'INVITATION_HISTORY_FAILURE';

//Types for invitation pic
export const INVITATION_REQUEST = 'INVITATION_REQUEST';
export const INVITATION_SUCCESS = 'INVITATION_SUCCESS';
export const INVITATION_FAILURE = 'INVITATION_FAILURE';

//Types for invitation pic
export const WALLET_DETAILS_REQUEST = 'WALLET_DETAILS_REQUEST';
export const WALLET_DETAILS_SUCCESS = 'WALLET_DETAILS_SUCCESS';
export const WALLET_DETAILS_FAILURE = 'WALLET_DETAILS_FAILURE';

//Types for invitation pic
export const GET_VOUCHER_CODE_REQUEST = 'GET_VOUCHER_CODE_REQUEST';
export const GET_VOUCHER_CODE_SUCCESS = 'GET_VOUCHER_CODE_SUCCESS';
export const GET_VOUCHER_CODE_FAILURE = 'GET_VOUCHER_CODE_FAILURE';

//Types for My Package
export const MY_PACKAGE_REQUEST = 'MY_PACKAGE_REQUEST';
export const MY_PACKAGE_REQUEST_SUCCESS = 'MY_PACKAGE_REQUEST_SUCCESS';
export const MY_PACKAGE_REQUEST_FAILURE = 'MY_PACKAGE_REQUEST_FAILURE';

//Types for My Package Details
export const MY_PACKAGE_DETAIL_REQUEST = 'MY_PACKAGE_DETAIL_REQUEST';
export const MY_PACKAGE_DETAIL_REQUEST_SUCCESS = 'MY_PACKAGE_DETAIL_REQUEST_SUCCESS';
export const MY_PACKAGE_DETAIL_REQUEST_FAILURE = 'MY_PACKAGE_DETAIL_REQUEST_FAILURE';

//Types for My Package Details
export const PICK_UP_REQUEST = 'PICK_UP_REQUEST';
export const PICK_UP_REQUEST_SUCCESS = 'PICK_UP_REQUEST_SUCCESS';
export const PICK_UP_REQUEST_FAILURE = 'PICK_UP_REQUEST_FAILURE';

//Types for GiftCard object
export const GIFT_CARD_OBJ_TRACK = 'GIFT_CARD_OBJ_TRACK';
export const GIFT_CARD_OBJ_SUCCESS = 'GIFT_CARD_OBJ_SUCCESS';
export const GIFT_CARD_OBJ_CLEAR = 'GIFT_CARD_OBJ_CLEAR';

//Types for giftcard create
export const GIFT_CARD_REQUEST = 'GIFT_CARD_REQUEST';
export const GIFT_CARD_SUCCESS = 'GIFT_CARD_SUCCESS';
export const GIFT_CARD_FAILURE = 'GIFT_CARD_FAILURE';

//Types for app settings
export const BIOMETRIC_LOGIN_SETTINGS = 'BIOMETRIC_LOGIN_SETTINGS';
export const BIOMETRIC_ICON_SHOW = 'BIOMETRIC_ICON_SHOW';
export const BIOMETRIC_ICON_HIDE = 'BIOMETRIC_ICON_HIDE';
export const FACE_ID_ICON_SHOW = 'FACE_ID_ICON_SHOW';
export const FACE_ID_ICON_HIDE = 'FACE_ID_ICON_HIDE';

// types for add card for billing
export const BILLING_TRACK = 'BILLING_TRACK';
export const BILLING_SUCCESS = 'BILLING_SUCCESS';
export const BILLING_FAILURE = 'BILLING_FAILURE';
export const BILLING_CLEAR = 'BILLING_CLEAR';

// types for get billing details
export const GET_BILLING_REQUEST = 'GET_BILLING_REQUEST';
export const GET_BILLING_SUCCESS = 'GET_BILLING_SUCCESS';
export const GET_BILLING_FAILURE = 'GET_BILLING_FAILURE';